// GENERATED BY scripts/gen-rung-types.mjs FROM rungs.json — DO NOT EDIT.
// Run `node scripts/gen-rung-types.mjs` after changing rungs.json. CI fails if this drifts.
//
// rungs.json is the single authority on what a rung is. These types exist so the shape-routed
// shell's routing switch is exhaustive at COMPILE time: add a rung or a shape to the manifest
// without adding a branch and tsc fails, instead of a rung silently rendering nothing.

/** Every rung in the ladder, in ordinal order. */
export type RungId = "langchain" | "langgraph" | "deepagents" | "open-swe" | "software-developer-agent";

/**
 * Interaction shape. #23 ruled this is a declared rung property and the shell routes by it.
 *
 * NOTE: a shape is NOT a stream topology. `run` does not mean "one run". Real Open SWE
 * registers three graphs (manager/planner/programmer) that do not share a run, so anything
 * describing threads, runs, or endpoints belongs in the shape handler, never here.
 * See apps/open-swe/docs/LOCAL-AGENT.md, "Topology: this backend is single-run".
 */
export type RungShape = "conversation" | "run";

/** Availability. `planned` rungs have no files and no target — render them without a link. */
export type RungState = "implemented" | "external-required" | "planned";

/**
 * Where the shell sends you for a rung. Deliberately a discriminated union: "one rung = one
 * route" cannot express the ladder as it actually exists. Rungs 1-3 share ONE surface and are
 * selected by a param; rung 4 is a whole app on a DIFFERENT ORIGIN; rung 5 has no target.
 */
export type RungTarget =
  | { readonly kind: "param"; readonly app: string; readonly route: string; readonly param: string; readonly value: string }
  | { readonly kind: "origin"; readonly app: string; readonly originEnv: string; readonly originFallback: string; readonly route: string }
  | { readonly kind: "route"; readonly app: string; readonly route: string }
  | { readonly kind: "none" };

export interface Rung {
  readonly id: RungId;
  readonly ordinal: number;
  readonly shape: RungShape;
  readonly state: RungState;
  readonly requires: readonly RungId[];
  /** Language planes owning files for this rung — drives the 8-job severability matrix. */
  readonly languages: readonly ("ts" | "py")[];
  readonly target: RungTarget;
}

export const RUNG_IDS = ["langchain", "langgraph", "deepagents", "open-swe", "software-developer-agent"] as const;
export const RUNG_SHAPES = ["conversation", "run"] as const;

export const RUNGS: readonly Rung[] = [
  {
    id: "langchain",
    ordinal: 1,
    shape: "conversation",
    state: "implemented",
    requires: [],
    languages: ["ts", "py"],
    target: {"kind":"param","app":"example","route":"/","param":"aiBackend","value":"langchain"},
  },
  {
    id: "langgraph",
    ordinal: 2,
    shape: "conversation",
    state: "implemented",
    requires: ["langchain"],
    languages: ["ts", "py"],
    target: {"kind":"param","app":"example","route":"/","param":"aiBackend","value":"langgraph"},
  },
  {
    id: "deepagents",
    ordinal: 3,
    shape: "conversation",
    state: "implemented",
    requires: ["langgraph"],
    languages: ["ts", "py"],
    target: {"kind":"param","app":"example","route":"/","param":"aiBackend","value":"deepagents"},
  },
  {
    id: "open-swe",
    ordinal: 4,
    shape: "run",
    state: "implemented",
    requires: ["deepagents"],
    languages: ["ts"],
    target: {"kind":"origin","app":"open-swe","originEnv":"NEXT_PUBLIC_QUEUE_URL","originFallback":"http://localhost:3001","route":"/"},
  },
  {
    id: "software-developer-agent",
    ordinal: 5,
    shape: "run",
    state: "planned",
    requires: ["open-swe"],
    languages: ["ts"],
    target: {"kind":"none"},
  },
] as const;

/** Lookup by id. Total over RungId, so callers need no undefined check. */
export const RUNG_BY_ID: Readonly<Record<RungId, Rung>> = Object.fromEntries(
  RUNGS.map((r) => [r.id, r])
) as Readonly<Record<RungId, Rung>>;

/**
 * Rungs a fork retains when ejected to `target` — the transitive closure of `requires`,
 * lowest ordinal first. Each rung is a superset of the concerns below it, so ejecting never
 * leaves a bare single rung.
 */
export function retainedRungs(target: RungId): readonly Rung[] {
  const keep = new Set<RungId>();
  const visit = (id: RungId) => {
    if (keep.has(id)) return;
    keep.add(id);
    RUNG_BY_ID[id].requires.forEach(visit);
  };
  visit(target);
  return RUNGS.filter((r) => keep.has(r.id));
}

/** Exhaustiveness helper: `default: return assertNever(shape)` fails to compile on a new shape. */
export function assertNever(x: never): never {
  throw new Error(`Unhandled rung variant: ${JSON.stringify(x)}`);
}
