// GENERATED BY scripts/gen-rung-types.mjs FROM rungs.json — DO NOT EDIT.
// Run `node scripts/gen-rung-types.mjs` after changing rungs.json. CI fails if this drifts.
//
// rungs.json is the single authority on what a rung is. These types exist so the shape-routed
// shell's routing switch is exhaustive at COMPILE time: add a rung or a shape to the manifest
// without adding a branch and tsc fails, instead of a rung silently rendering nothing.

/** Every rung in the ladder, in ordinal order. */
export type RungId = "langchain" | "langgraph" | "deepagents" | "open-swe" | "software-developer-agent";

/**
 * Interaction shape. #23 ruled this is a declared rung property and the shell routes by it.
 *
 * NOTE: a shape is NOT a stream topology. `run` does not mean "one run". Real Open SWE
 * registers three graphs (manager/planner/programmer) that do not share a run, so anything
 * describing threads, runs, or endpoints belongs in the shape handler, never here.
 * See apps/open-swe/docs/LOCAL-AGENT.md, "Topology: this backend is single-run".
 */
export type RungShape = "conversation" | "run";

/** Availability. `planned` rungs have no files and no target — render them without a link. */
export type RungState = "implemented" | "external-required" | "planned";

/**
 * Where the shell sends you for a rung. Deliberately a discriminated union: "one rung = one
 * route" cannot express the ladder as it actually exists. Rungs 1-3 share ONE surface and are
 * selected by a param; rung 4 is a whole app on a DIFFERENT ORIGIN; rung 5 has no target.
 */
export type RungTarget =
  | { readonly kind: "param"; readonly app: string; readonly route: string; readonly param: string; readonly value: string }
  | { readonly kind: "origin"; readonly app: string; readonly originEnv: string; readonly originFallback: string; readonly route: string }
  | { readonly kind: "none" };
// There is deliberately no "route" variant. No rung has its own in-app route, and a variant
// nothing exercises cannot be tested, rots, and reads to a reviewer as "handled" when nothing
// proved it. Adding one later is a schema line plus a compile error from assertNever() pointing
// at the exact switch that needs a branch — the compiler tells the next person where to go.

export type RuntimeId = string;

export interface RungRuntime {
  /**
   * Topologies this (rung, runtime) pair serves.
   *
   * AN EMPTY ARRAY MEANS ONE CELL WITH NO TOPOLOGY AXIS — NOT ZERO CELLS. Prefer matrixCells()
   * over reading this directly; that rule is encoded once, there, deliberately.
   */
  readonly topologies: readonly string[];
  readonly topologiesSource?: string;
}

export interface Rung {
  readonly id: RungId;
  readonly ordinal: number;
  readonly shape: RungShape;
  readonly state: RungState;
  readonly requires: readonly RungId[];
  /** Language planes owning files for this rung — drives the 8-job severability matrix. */
  readonly languages: readonly ("ts" | "py")[];
  /**
   * Which backends SERVE this rung, and what each offers.
   *
   * NOT the same as languages, which is which planes hold files this rung OWNS. Rung 1 has
   * languages [ts, py] — it owns a TS adapter and two Python modules — but runtimes
   * [django, fastapi], because no node runtime serves it. Close enough to be conflated,
   * different enough that conflating them would be wrong.
   */
  readonly runtimes: Readonly<Record<RuntimeId, RungRuntime>>;
  readonly target: RungTarget;
}

/** One cell of the behavioural matrix: a (rung, runtime, topology?) triple. */
export interface MatrixCell {
  readonly rung: RungId;
  readonly runtime: RuntimeId;
  /** undefined when the pair has no topology axis — every run-shaped rung. */
  readonly topology?: string;
  readonly shape: RungShape;
  readonly state: RungState;
}

export const RUNG_IDS = ["langchain", "langgraph", "deepagents", "open-swe", "software-developer-agent"] as const;
export const RUNG_SHAPES = ["conversation", "run"] as const;

export const RUNGS: readonly Rung[] = [
  {
    id: "langchain",
    ordinal: 1,
    shape: "conversation",
    state: "implemented",
    requires: [],
    languages: ["ts", "py"],
    runtimes: {"django":{"topologies":["react","plan-execute"],"topologiesSource":"apps/django-backend/deepagents_backend/ai_backends/langchain.py"},"fastapi":{"topologies":["react","plan-execute"],"topologiesSource":"apps/fastapi-backend/ai_backends/langchain.py"}},
    target: {"kind":"param","app":"example","route":"/r/[rung]","param":"rung","value":"langchain"},
  },
  {
    id: "langgraph",
    ordinal: 2,
    shape: "conversation",
    state: "implemented",
    requires: ["langchain"],
    languages: ["ts", "py"],
    runtimes: {"django":{"topologies":["react","plan-execute"],"topologiesSource":"apps/django-backend/deepagents_backend/ai_backends/langgraph.py"},"fastapi":{"topologies":["react","plan-execute"],"topologiesSource":"apps/fastapi-backend/ai_backends/langgraph.py"}},
    target: {"kind":"param","app":"example","route":"/r/[rung]","param":"rung","value":"langgraph"},
  },
  {
    id: "deepagents",
    ordinal: 3,
    shape: "conversation",
    state: "implemented",
    requires: ["langgraph"],
    languages: ["ts", "py"],
    runtimes: {"django":{"topologies":["react","plan-execute","deep-research"],"topologiesSource":"apps/django-backend/deepagents_backend/ai_backends/deepagents.py"},"fastapi":{"topologies":["react","plan-execute","deep-research"],"topologiesSource":"apps/fastapi-backend/ai_backends/deepagents.py"}},
    target: {"kind":"param","app":"example","route":"/r/[rung]","param":"rung","value":"deepagents"},
  },
  {
    id: "open-swe",
    ordinal: 4,
    shape: "run",
    state: "implemented",
    requires: ["deepagents"],
    languages: ["ts"],
    runtimes: {"node":{"topologies":[]}},
    target: {"kind":"origin","app":"open-swe","originEnv":"NEXT_PUBLIC_QUEUE_URL","originFallback":"http://localhost:3001","route":"/"},
  },
  {
    id: "software-developer-agent",
    ordinal: 5,
    shape: "run",
    state: "implemented",
    requires: ["open-swe"],
    languages: ["ts"],
    runtimes: {"node":{"topologies":[]}},
    target: {"kind":"none"},
  },
] as const;

/** Lookup by id. Total over RungId, so callers need no undefined check. */
export const RUNG_BY_ID: Readonly<Record<RungId, Rung>> = Object.fromEntries(
  RUNGS.map((r) => [r.id, r])
) as Readonly<Record<RungId, Rung>>;

/**
 * Rungs a fork retains when ejected to `target` — the transitive closure of `requires`,
 * lowest ordinal first. Each rung is a superset of the concerns below it, so ejecting never
 * leaves a bare single rung.
 */
export function retainedRungs(target: RungId): readonly Rung[] {
  const keep = new Set<RungId>();
  const visit = (id: RungId) => {
    if (keep.has(id)) return;
    keep.add(id);
    RUNG_BY_ID[id].requires.forEach(visit);
  };
  visit(target);
  return RUNGS.filter((r) => keep.has(r.id));
}

/**
 * Every cell of the behavioural matrix.
 *
 * THE ONE PLACE THE EMPTY-TOPOLOGIES RULE LIVES. An empty topologies array means one cell with
 * no topology axis, not zero cells — a run-shaped rung still has to be exercised. Three
 * consumers derive matrix arity from this manifest, and a semantic that can be guessed wrong
 * should be a function rather than a comment, so that none of them re-derives it.
 *
 * The ladder is ragged: deep-research exists on the deepagents rung only, on both of its
 * runtimes. A uniform 3 x 2 x 3 grid emits 18 cells, four of which do not exist.
 *
 * It was raggeder. deep-research lived in deepagents x fastapi ALONE until django's
 * RESEARCH_TOOLS gained it, so this comment used to read "exists only in deepagents x
 * fastapi" and the cell count used to be 15. The asymmetry was closed deliberately, and
 * the raggedness that remains is now at the RUNG level rather than the runtime level:
 * langchain and langgraph have no deep-research on either runtime.
 *
 * Callers wanting only runnable cells should filter on state — a planned rung has no
 * implementation to exercise.
 */
export function matrixCells(): readonly MatrixCell[] {
  const out: MatrixCell[] = [];
  for (const rung of RUNGS) {
    for (const [runtime, cfg] of Object.entries(rung.runtimes)) {
      if (cfg.topologies.length === 0) {
        out.push({ rung: rung.id, runtime, shape: rung.shape, state: rung.state });
      } else {
        for (const topology of cfg.topologies) {
          out.push({ rung: rung.id, runtime, topology, shape: rung.shape, state: rung.state });
        }
      }
    }
  }
  return out;
}

/**
 * Resolve a rung's URL. The substitution rule, in one place: the literal [param] in
 * target.route is replaced by target.value.
 *
 * Returns null when there is nothing to link to — a planned rung — so callers render it as
 * declared-but-absent rather than offering a dead link.
 */
export function rungHref(rung: Rung, env: Record<string, string | undefined> = {}): string | null {
  const t = rung.target;
  if (t.kind === "none") return null;
  if (t.kind === "param") return t.route.replace(`[${t.param}]`, t.value);
  return `${env[t.originEnv] ?? t.originFallback}${t.route}`;
}

/** Exhaustiveness helper: `default: return assertNever(shape)` fails to compile on a new shape. */
export function assertNever(x: never): never {
  throw new Error(`Unhandled rung variant: ${JSON.stringify(x)}`);
}
