/**
 * @deepagents-nextjs/rungs — the rung manifest as typed data.
 *
 * rungs.json at the repo root is the single authority on what a rung is. This package is the
 * TypeScript face of it, generated by scripts/gen-rung-types.mjs and checked for drift in CI.
 *
 * It exists as a workspace package rather than a root file for one reason: a root file cannot
 * be imported cleanly from apps/ (each app's tsconfig `include` is rooted at the app and its
 * `paths` replaces rather than extends the base), and the alternative — generating a copy into
 * each consumer — reintroduces exactly the second-list problem this manifest exists to remove.
 * One source, one package, however many consumers.
 *
 * This package is `shared`: it survives every eject, at every rung.
 */
export * from "./generated";
